version: '3.3'

services:
  backend:
    build: .
    container_name: spotify_clone_api
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - spotify_network

networks:
  spotify_network:
    driver: bridge
