name: Deploy Backend to Oracle Cloud

on:
  push:
    branches:
      - main # O el nombre de tu rama principal (master, main, etc.)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar por SSH y actualizar servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/backend/spotify-clone-flutter/backend
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker image prune -f